-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 17:22:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Código Postal` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Código Postal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Zona_Código Postal` INT NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `fk_Calle_Zona1_idx` (`Zona_Código Postal` ASC) VISIBLE,
  CONSTRAINT `fk_Calle_Zona1`
    FOREIGN KEY (`Zona_Código Postal`)
    REFERENCES `mydb`.`Zona` (`Código Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construcción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construcción` (
  `Número` INT NOT NULL,
  `Año` DATE NULL,
  `Calle_Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Número`),
  INDEX `fk_Construcción_Calle1_idx` (`Calle_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Construcción_Calle1`
    FOREIGN KEY (`Calle_Nombre`)
    REFERENCES `mydb`.`Calle` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Direccion` VARCHAR(100) NOT NULL,
  `numero` INT NULL,
  `Coordenadas` VARCHAR(45) NULL,
  `Construcción_Número` INT NOT NULL,
  PRIMARY KEY (`Construcción_Número`),
  INDEX `fk_Bloque_Construcción1_idx` (`Construcción_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Bloque_Construcción1`
    FOREIGN KEY (`Construcción_Número`)
    REFERENCES `mydb`.`Construcción` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `idPiso` VARCHAR(10) NOT NULL,
  `Bloque_Construcción_Número` INT NOT NULL,
  PRIMARY KEY (`Bloque_Construcción_Número`, `idPiso`),
  INDEX `fk_Piso_Bloque1_idx` (`Bloque_Construcción_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Piso_Bloque1`
    FOREIGN KEY (`Bloque_Construcción_Número`)
    REFERENCES `mydb`.`Bloque` (`Construcción_Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unidad Familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unidad Familiar` (
  `Dirección` VARCHAR(100) NOT NULL,
  `Coordenadas` VARCHAR(45) NULL,
  `Construcción_Número` INT NOT NULL,
  PRIMARY KEY (`Construcción_Número`),
  INDEX `fk_Unidad Familiar_Construcción1_idx` (`Construcción_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Unidad Familiar_Construcción1`
    FOREIGN KEY (`Construcción_Número`)
    REFERENCES `mydb`.`Construcción` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Unidad Familiar_Construcción_Número` INT NOT NULL,
  `Piso_Bloque_Construcción_Número` INT NOT NULL,
  `Piso_idPiso` VARCHAR(10) NOT NULL,
  `Persona_DNI` INT NOT NULL,
  `Persona_Unidad Familiar_Construcción_Número` INT NOT NULL,
  PRIMARY KEY (`DNI`, `Unidad Familiar_Construcción_Número`),
  INDEX `fk_Persona_Unidad Familiar1_idx` (`Unidad Familiar_Construcción_Número` ASC) VISIBLE,
  INDEX `fk_Persona_Piso1_idx` (`Piso_Bloque_Construcción_Número` ASC, `Piso_idPiso` ASC) VISIBLE,
  INDEX `fk_Persona_Persona1_idx` (`Persona_DNI` ASC, `Persona_Unidad Familiar_Construcción_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Unidad Familiar1`
    FOREIGN KEY (`Unidad Familiar_Construcción_Número`)
    REFERENCES `mydb`.`Unidad Familiar` (`Construcción_Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Piso1`
    FOREIGN KEY (`Piso_Bloque_Construcción_Número` , `Piso_idPiso`)
    REFERENCES `mydb`.`Piso` (`Bloque_Construcción_Número` , `idPiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Persona1`
    FOREIGN KEY (`Persona_DNI` , `Persona_Unidad Familiar_Construcción_Número`)
    REFERENCES `mydb`.`Persona` (`DNI` , `Unidad Familiar_Construcción_Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coordenadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coordenadas` (
  `numero` INT NOT NULL,
  `Coordendanas x` INT NULL,
  `Coordenadas Y` INT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
