-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 17:30:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Nombre` VARCHAR(40) NOT NULL,
  `Ubicación` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `Cödigo Zona` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Vivero_Nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Cödigo Zona`, `Vivero_Nombre`),
  INDEX `fk_Zona_Vivero_idx` (`Vivero_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Zona_Vivero`
    FOREIGN KEY (`Vivero_Nombre`)
    REFERENCES `mydb`.`Vivero` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Código Barras` VARCHAR(12) NOT NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`Código Barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Seguridad Social` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `nº cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `Código` VARCHAR(15) NOT NULL,
  `nº productos` INT NULL,
  `DNI` INT NULL,
  `Cliente_DNI` INT NOT NULL,
  `Empleado_DNI` INT NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_DNI` ASC) VISIBLE,
  INDEX `fk_Pedido_Empleado1_idx` (`Empleado_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_DNI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY (`Empleado_DNI`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Producto` (
  `Pedido_Código` VARCHAR(15) NOT NULL,
  `Producto_Código Barras` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Pedido_Código`, `Producto_Código Barras`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`Producto_Código Barras` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`Pedido_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`Pedido_Código`)
    REFERENCES `mydb`.`Pedido` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`Producto_Código Barras`)
    REFERENCES `mydb`.`Producto` (`Código Barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento_has_Producto` (
  `Departamento_Cödigo Zona` INT NOT NULL,
  `Departamento_Vivero_Nombre` VARCHAR(40) NOT NULL,
  `Producto_Código Barras` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Departamento_Cödigo Zona`, `Departamento_Vivero_Nombre`, `Producto_Código Barras`),
  INDEX `fk_Departamento_has_Producto_Producto1_idx` (`Producto_Código Barras` ASC) VISIBLE,
  INDEX `fk_Departamento_has_Producto_Departamento1_idx` (`Departamento_Cödigo Zona` ASC, `Departamento_Vivero_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_has_Producto_Departamento1`
    FOREIGN KEY (`Departamento_Cödigo Zona` , `Departamento_Vivero_Nombre`)
    REFERENCES `mydb`.`Departamento` (`Cödigo Zona` , `Vivero_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_has_Producto_Producto1`
    FOREIGN KEY (`Producto_Código Barras`)
    REFERENCES `mydb`.`Producto` (`Código Barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento_has_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento_has_Empleado` (
  `Departamento_Cödigo Zona` INT NOT NULL,
  `Departamento_Vivero_Nombre` VARCHAR(40) NOT NULL,
  `Empleado_DNI` INT NOT NULL,
  PRIMARY KEY (`Departamento_Cödigo Zona`, `Departamento_Vivero_Nombre`, `Empleado_DNI`),
  INDEX `fk_Departamento_has_Empleado_Empleado1_idx` (`Empleado_DNI` ASC) VISIBLE,
  INDEX `fk_Departamento_has_Empleado_Departamento1_idx` (`Departamento_Cödigo Zona` ASC, `Departamento_Vivero_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_has_Empleado_Departamento1`
    FOREIGN KEY (`Departamento_Cödigo Zona` , `Departamento_Vivero_Nombre`)
    REFERENCES `mydb`.`Departamento` (`Cödigo Zona` , `Vivero_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_DNI`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
